### ISSUE TITLE
Warnings log across different servers.

### ISSUE THREAD

**Issue by whyadamsalt** [Cobweb-Development/minimal#7]
If you gain a warning in one server, the warning carries between servers rather than remaining in the server you were warned in.
We need to ensure that warnings do not carry across servers.

**Comment by OfekShochat** [comment]
Possible Implementation and explanation:
We use a local file called warnings.json to log warnings. So if you execute the same bot in the same directory it will read that warnings.json. 
This can be Implemented with guild Id also as an additional key and then a sub json will be the warnings to that server/guild

**Comment by whyadamsalt** [comment]
> Possible Implementation and explanation:
> We use a local file called warnings.json to log warnings. So if you execute the same bot in the same directory it will read that warnings.json.
> This can be Implemented with guild Id also as an additional key and then a sub json will be the warnings to that server/guild

Do you think you would be able to work on this and fix it?

**Comment by OfekShochat** [comment]
Working on it :)

**Comment by whyadamsalt** [comment]
Thank you!
